#!/bin/bash
set -o errexit

CXX="g++"
ARC="ar"
TEMP="/home/lianjin/BUILD_TEMP/"
OUTPUT="/home/lianjin/BUILD_OUTPUT/"

REPO="single_module/"
MODULE="example"
TYPE="exec"
COPT="-g -fPIC"
WORKSPACE="example/"
SRCS="main.cpp"
HDRS=""

INC=" -I"$WORKSPACE" -I"$OUTPUT"single_module/include/"
LINK=" -L"$OUTPUT"single_module/lib -ltest"
THIS_TEMP=$TEMP$REPO
THIS_OUTPUT=$OUTPUT$REPO

res_change=false
object_list=""
for s in ${SRCS[@]}; do
    src=$WORKSPACE$s
    object_file=${THIS_TEMP}${src}".o"
    object_list+=" "$object_file
    depend_file=${THIS_TEMP}${src}".d"
    if [ ! -f ${object_file} ]; then
	res_change=true
	$CXX -o ${object_file} -c ${src} $COPT $INC
    else
	if [ ! -f $depend_file ]; then
	    $CXX -MM ${src} $INC > $depend_file
    	else
	    depend_file_time=`stat -c %Y ${depend_file}`
	    # depend file exsit, whever we should rebuild it
	    headers=`awk -F ":" '{print $2}' $depend_file | sed 's/\\\\/ /g'`
	    depend_file_change=false
	    for h in ${headers[@]}; do
		if [ ! -f $h ]; then
		    depend_file_change=true
		    break
		fi
		header_file_time=`stat -c %Y $h`
		if [ $header_file_time -gt $depend_file_time ]; then
		    depend_file_change=true
		    break
		fi
	    done
	    if [ $depend_file_change = true ]; then
		$CXX -MM ${src} $INC > $depend_file
	    fi
	fi #
	headers=`awk -F ":" '{print $2}' $depend_file | sed 's/\\\\/ /g'`
	object_file_change=false
	object_file_time=`stat -c %Y ${object_file}`
	for h in ${headers[@]}; do
	    header_file_time=`stat -c %Y $h`
	    if [ $header_file_time -gt $object_file_time ]; then
		$CXX -o ${object_file} -c ${src} $COPT $INC
		res_change=true
	    fi
	done
    fi
done

if [ $res_change ]; then
    if [ $TYPE = "static" ]; then
	$ARC -r $THIS_OUTPUT"lib/""lib"$MODULE".a" $object_list $LINK
    elif [ $TYPE = "shared" ]; then
	$CXX -shared -o $THIS_OUTPUT"lib/""lib"$MODULE".so" $object_list $COPT $LINK
    else
        $CXX -o $THIS_OUTPUT"bin/"$MODULE $object_list $COPT $LINK
    fi
fi

for h in ${HDRS[@]}; do
    cp $WORKSPACE$h $THIS_OUTPUT"include/"
done
